# == Variables ==
# 
# You can define here your project Variables.
# If you want to define/override a Variable for a specific Environment, 
# add an additional ‘variables.yaml’ file in a subdirectory in the ‘Config’ folder: 
# '<project>/Config/_<environment>/variables.yaml
#
Variables:
  mailstore-connector:
    dummy:
      # [enum: pop3, pop3s, imap, imaps]
      protocol: 'imap'
      # Host for store connection
      host: 'localhost'
      # Port for store connection (only needed if not default)
      port: -1
      # User name for store connection
      user: 'debug@localdomain.test'
      # Password for store connection
      # [password]
      password: 'pass'
      # show debug output for connection
      debug: true
      # Additional properties for store connection,
      # see https://javaee.github.io/javamail/docs/api/com/sun/mail/imap/package-summary.html
      properties:
          mail.imaps.ssl.checkserveridentity: false
          mail.imaps.ssl.trust: '*'
          # only set below credential when you go with oauth2
          # mail.imaps.auth.mechanisms: 'XOAUTH2'
          # mail.imaps.sasl.enable: 'true'
          # mail.imaps.sasl.mechanisms: 'XOAUTH2'
          
      # [basic, oauth2] basic: username and password, oauth2: currently only support OAuth2 client credentials grant flow
      auth: 'basic'
      
      # only set below credential when you go with oauth2
      # tenant to use for OAUTH2 request.
      # set the Azure Directory (tenant) ID, for application requests.
      tenantId: ''
      # Your Azure Application (client) ID, used for OAuth2 authentication
      appId: ''
      # Secret key from your applications "certificates & secrets" (client secret)
      secretKey: ''
      # for client_credentials: https://outlook.office365.com/.default
      scope: ''
      #[client_credentials]
      grantType: ''
      # link url to get token
      tokenUrl:
        tokenUrlPrefix: 'login.microsoftonline.com'
        tokenUrlSuffix: '%s/oauth2/v2.0/token'