# == Variables ==
# 
# You can define here your project Variables.
# If you want to define/override a Variable for a specific Environment, 
# add an additional ‘variables.yaml’ file in a subdirectory in the ‘Config’ folder: 
# '<project>/Config/_<environment>/variables.yaml
#
Variables:
  mailstore-connector:
    dummy:
      # [enum: pop3, pop3s, imap, imaps]
      protocol: 'imap'
      # Host for store connection
      host: 'localhost'
      # Port for store connection (only needed if not default)
      port: -1
      # User name for store connection
      user: 'debug@localdomain.test'
      # Password for store connection
      # [password]
      password: 'pass'
      # show debug output for connection
      debug: true
      # Additional properties for store connection,
      # see https://javaee.github.io/javamail/docs/api/com/sun/mail/imap/package-summary.html
      properties:
          mail.imaps.ssl.checkserveridentity: false
          mail.imaps.ssl.trust: '*'
          
      # [basic, oauth2] basic: username and password, oauth2: OAuth2 Client Credentials grant flow, OAuth2 Authorization code flow, OAuth2 device authorization grant flow.
      auth: 'basic'
      
      # tenant to use for OAUTH2 request.
      # the default 'common' fits for user delegate requests.
      # set the Azure Directory (tenant) ID, for application requests.
      tenantId: ''
      # Your Azure Application (client) ID
      appId: ''
      # Secret key from your applications "certificates & secrets" (client secret)
      secretKey: ''
      # permissions to request access to.
      # you may exclude or add some, as your azure administrator allows or restricts them.
      # for client_credentials: https://outlook.office365.com/.default
      scope: ''
      #[client_credentials, authorization_code]
      grantType: ''