# yaml-language-server: $schema=https://json-schema.axonivy.com/app/12.0.0/variables.json
#
# Dear Bug Hunter,
# This credential is intentionally included for educational purposes only and does not provide access to any production systems.
# Please do not submit it as part of our bug bounty program.
#
# == Variables ==
#
# You can define here your project Variables.
# If you want to define/override a Variable for a specific Environment, 
# add an additional ‘variables.yaml’ file in a subdirectory in the ‘Config’ folder: 
# '<project>/Config/_<environment>/variables.yaml
#
Variables:
  mailstore-connector:
    localhost-imap:
      # [enum: pop3, pop3s, imap, imaps]
      protocol: imap
      # Host for store connection
      host: localhost
      # Port for store connection (only needed if not default)
      port: "-1"
      # User name for store connection
      user: debug@localdomain.test
      # Password for store connection
      #[password]
      password: ${decrypt:j14yX4PdWOjm4y7ULz35oPQGH+WEp8uS5lji2ZHMtd4=}
      # show debug output for connection
      debug: "true"
      # Additional properties for store connection,
      # see https://javaee.github.io/javamail/docs/api/com/sun/mail/imap/package-summary.html
      properties:
        mail:
          imaps:
            ssl:
              checkserveridentity: "false"
              trust: "*"
      userPasswordProvider: ""
      # only set below credential when you go with oauth2
      # tenant to use for OAUTH2 request.
      # set the Azure Directory (tenant) ID, for application requests.
      tenantId: ""
      # Your Azure Application (client) ID, used for OAuth2 authentication
      appId: ""
      # Secret key from your applications "certificates & secrets" (client secret)
      secretKey: ""
      # for client_credentials: https://outlook.office365.com/.default
      scope: ""
      grantType: ""
    localhost-imap-basic-authentication:
      # [enum: pop3, pop3s, imap, imaps]
      protocol: imap
      # Host for store connection
      host: localhost
      # Port for store connection (only needed if not default)
      port: "-1"
      # User name for store connection
      user: debug@localdomain.test
      # Password for store connection
      #[password]
      password: ${decrypt:XZqAi7eMCFxdtNs1TPnCWA==}
      # show debug output for connection
      debug: "true"
      # Additional properties for store connection,
      # see https://javaee.github.io/javamail/docs/api/com/sun/mail/imap/package-summary.html
      properties:
        mail:
          imaps:
            ssl:
              checkserveridentity: "false"
              trust: "*"
      userPasswordProvider: com.axonivy.connector.oauth.BasicUserPasswordProvider
    localhost-imap-azure-oauth2-authentication:
      # [enum: pop3, pop3s, imap, imaps]
      protocol: imap
      # Host for store connection
      host: localhost
      # Port for store connection (only needed if not default)
      port: "-1"
      # User name for store connection
      user: debug@localdomain.test
      # Password for store connection
      #[password]
      password: ${decrypt:}
      # show debug output for connection
      debug: "true"
      # Additional properties for store connection,
      # see https://javaee.github.io/javamail/docs/api/com/sun/mail/imap/package-summary.html
      properties:
        mail:
          imaps:
            ssl:
              checkserveridentity: "false"
              trust: "*"
            auth:
              # only set below credential when you go with oauth2
              mechanisms: XOAUTH2
            sasl:
              enable: "true"
              mechanisms: XOAUTH2
      userPasswordProvider: com.axonivy.connector.oauth.AzureOauth2UserPasswordProvider
      # only set below credential when you go with oauth2
      # tenant to use for OAUTH2 request.
      # set the Azure Directory (tenant) ID, for application requests.
      tenantId: ""
      # Your Azure Application (client) ID, used for OAuth2 authentication
      appId: ""
      # Secret key from your applications "certificates & secrets" (client secret)
      secretKey: ""
      # for client_credentials/password: https://outlook.office365.com/.default
      scope: ""
      grantType: ""
  # login microsoft azure
  azureOAuth:
    loginUrl: login.microsoftonline.com
