name: Dev-Build

on:
  push:
  schedule:
    - cron:  '21 21 * * *'
  workflow_dispatch:

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  build:
    uses: axonivy-market/github-workflows/.github/workflows/dev.yml@v4
    with:
        ivyVersion: nightly-10.0
        testerVersion: 10.0.16
        ivyPluginVersion: 10.0.17
